apiVersion: v1
kind: PersistentVolume
metadata:
  name: platform-clickhouse
  labels:
    app: clickhouse
    tier: storage
spec:
  capacity:
    storage: 64Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    name: platform-clickhouse
    namespace: default
  csi:
    driver: pd.csi.storage.gke.io
    volumeHandle: projects/open-targets-eu-dev/zones/europe-west1-d/disks/data-clickhouse
    fsType: ext4