apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - disk.yaml
  #- pv.yaml
  #- pvc.yaml
  #- snapshot.yaml
  #- application.yaml

patches:
  - path: patch-disk.yaml
    target:
      kind: Disk
      name: data-clickhouse
    options:
      allowNameChange: true