apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - environment.yaml
  #- gce-disk.yaml
  #- source-pv.yaml
  #- source-pvc.yaml
  #- source-pvc-snapshot.yaml
  #- clickhouse.yaml

#configurations:
#  - namespace-transformer.yaml