apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  #- stack-disk.yaml
  #- stack-pv.yaml
  #- stack-pvc.yaml
  #- stack-snapshot.yaml
  #- stack-application.yaml

#patches:
  #- path: patch-disk.yaml
  #  target:
  #    kind: Disk
  #    name: data-clickhouse
  #  options:
  #    allowNameChange: true
  #- path: patch-stack-name.yaml
  #  target:
  #    labelSelector: stack=clickhouse
  #  options:
  #    allowNameChange: true
configurations:
  - name-reference-pv.yaml