apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - environment.yaml
  #- gce-disk.yaml
  #- source-pv.yaml
  #- source-pvc.yaml
  #- source-pvc-snapshot.yaml
  #- clickhouse.yaml

configMapGenerator:
  - name: clickhouse-release-env
    literals:
      - namespace=ARGOCD_NAMESPACE  # ArgoCD can dynamically replace this

vars:
  - name: ARGOCD_NAMESPACE
    objref:
      kind: ConfigMap
      name: clickhouse-release-env
      apiVersion: v1
    fieldref:
      fieldpath: data.namespace

configurations:
  - environment.yaml