apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  #- stack-configuration.yaml
  - disk.yaml
  - pv.yaml
  - pvc.yaml
  #- snapshot.yaml
  #- application.yaml

#patches:
  #- path: patch-disk.yaml
  #  target:
  #    kind: Disk
  #    name: data-clickhouse
  #  options:
  #    allowNameChange: true
  #- path: patch-stack-name.yaml
  #  target:
  #    labelSelector: stack=clickhouse
  #  options:
  #    allowNameChange: true
configurations:
  - name-reference-pv.yaml