apiVersion: builtin
kind: NamespaceTransformer
metadata:
  name: not-important-to-example
setRoleBindingSubjects: none
#unsetOnly: true
fieldSpecs:
- path: data/namespace
  kind: ConfigMap
  name: clickhouse-release-env
  create: true