apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: platform-clickhouse
  labels:
    app: clickhouse
    tier: storage
spec:
  storageClassName: data-backend
  volumeName: platform-clickhouse
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 64Gi