apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: clickhouse-snapshot
  #namespace: playground-k8s
spec:
  volumeSnapshotClassName: data-backend
  source:
    persistentVolumeClaimName: platform-clickhouse
