apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-world
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/mbdebian/playground-k8s.git
    targetRevision: main
    path: app/overlays/main
    kustomize:
      commonAnnotationsEnvsubst: true
    plugin:
      env:
        - name: CTXT_DEPLOYMENT_NAMESPACE
          value: playground-k8s
  destination:
    namespace: playground-k8s
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true