apiVersion: v1
kind: Service
metadata:
  name: disco-world
spec:
  selector:
    app: disco-world
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: disco-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: disco-world
  template:
    metadata:
      labels:
        app: disco-world
    spec:
      containers:
        - name: disco-world
          image: "gcr.io/google-samples/hello-app:1.0"
          ports:
            - containerPort: 8080